name: Download and Extract Device Tree

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Download and extract device tree
      run: |
        curl -O https://download.lenovo.com/consumer/mobiles/tb_m10_fhd_rel_x605fc_s000071_190802_row.tar
        tar --keep-old-files --no-same-owner --no-same-permissions -xf tb_m10_fhd_rel_x605fc_s000071_190802_row.tar
        rm tb_m10_fhd_rel_x605fc_s000071_190802_row.tar
